### ISSUE TITLE
It is not accepting utf-8 accents

### ISSUE THREAD

**Issue by lf-araujo** [oblitum/dotfiles#3]
Thank you for MIMEmbelish, I write in the hope that you still use it and may be able to help me debug this. The script itself is ready for utf-8, however in my attempt to use it in mutt an  error occurs whenever I add an accent of any type (e.g. é).

The error message is: 

```
Traceback (most recent call last):
│  File "/home/luis/.local/bin/MIMEmbellish", line 238, in <module>
│    main()
│  File "/home/luis/.local/bin/MIMEmbellish", line 225, in main
│    message = email.message_from_file(sys.stdin)
│  File "/usr/lib/python3.6/email/__init__.py", line 54, in
                   │message_from_file
                   │    return Parser(*args, **kws).parse(fp)
                   │  File "/usr/lib/python3.6/email/parser.py", line 54, in parse
                   │    data = fp.read(8192)
                   │  File "/usr/lib/python3.6/codecs.py", line 321, in decode
                   │    (result, consumed) = self._buffer_decode(data, self.errors,
                   │final)
                   │UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position
                   │340: invalid continuation byte
```
- What do you suggest I should try?

**Comment by lf-araujo** [comment]
Thank you for this, it improved. The error message is gone, however the
email comes without the body. I start to suspect that the problem is in
vim, which is my main text editor.

- Do you have any charset configuration on your vimrc?

All the best,
lf

**Comment by oblitum** [comment]
In what sense does the email "comes"? You mean when you have it sent to your mailbox it's empty?
If it is not working right away for you try using `MIMEmbellish` from the command line step by step like I [exemplify in my blog post](http://nosubstance.me/post/mutt-secret-sauce/#mimembellish-the-email-embellisher).

Example for seeing:

```sh
cat mail.eml | MIMEmbellish
```

Example for sending:

```sh
cat mail.eml | MIMEmbellish | msmtp -a 'foo@example.com' 'foo@example.com'
```

There are email files you can grab [here](https://github.com/mikel/mail/tree/master/spec/fixtures/emails) to exercise that.

If that part is working, then the `sendmail` part is done and is correct, you'll have to check which other part of your chain is broken.

**Comment by oblitum** [comment]
Also, I use Vim and NeoVim and don't set anything for charset in my conf, on *nix it defaults to utf-8 in general.

**Comment by oblitum** [comment]
This is an example screenshot of gmail rendered output, in portuguese, no issues with accents:

![01 46 59_20-03-18](https://user-images.githubusercontent.com/1269815/48363300-c0d82200-e68c-11e8-9d0d-8c9f5ea702ce.png)

Edited with markdown in Vim, sent with mutt/msmtp/MIMEmbellish.

**Comment by oblitum** [comment]
Closing for inactivity.

**Comment by lf-araujo** [comment]
Thanks for the support,

I still could not figure out what I am doing wrong. Let's go by parts: 

1. Using the example in your blog post is no help, as it does not use Markdown markup, so for example if I try:

`curl --silent https://raw.githubusercontent.com/mikel/mail/master/spec/fixtures/emails/plain_emails/raw_email_simple.eml | MIMEmbellish | msmtp -a 'gmail' 'luis.nando@gmail.com'`

I get:
![image](https://user-images.githubusercontent.com/10139950/48939723-592b9d80-eefc-11e8-9d5a-f60fd5ee0956.png)

2. Using another eml file with point bullets, does not generate rich output:

`cat test.eml | MIMEmbellish | msmtp -a 'gmail' 'some@email.com'`

Generates:

![image](https://user-images.githubusercontent.com/10139950/48939790-92fca400-eefc-11e8-929a-ca0c3b9f51d4.png)

The content for this email reads:

```
Return-Path: <test@test.com>
Received: from mail-xxx.google.com (mail-xxx.google.com [0.0.0.0])
	by smtp.test.com (Postfix) with ESMTP id xxxx
	for <tester@test.com>; Wed,  2 Dec 2009 09:39:57 +0000 (UTC)
Received: by qyk6 with SMTP id 6so3112qyk.3
        for <tester@test.com>; Wed, 02 Dec 2009 01:39:53 -0800 (PST)
MIME-Version: 1.0
Received: by 0.0.0.0 with SMTP id xxx.000.0000000000000; Wed, 
	02 Dec 2009 01:39:53 -0800 (PST)
In-Reply-To: <8fc5086d0912020131y377ba0ccpf8f14783cfc3014a@test.com>
References: <8fc5086d0912020131y377ba0ccpf8f14783cfc3014a@test.com>
From: Tester 1 <tester1@test.com>
Date: Wed, 2 Dec 2009 22:39:33 +1300
Message-ID: <8fc5086d0912020139y1564ad32jb4f4209fa464f4a6@test.com>
Subject: Sending messages include last little bit
To: tester2@test.com
Content-Type: multipart/alternative; boundary=00c09fa216eb1bfc0a0479bba823

--00c09fa216eb1bfc0a0479bba823
Content-Type: text/plain; charset=ISO-8859-1

When sending email:
* From Hotmail you get the ads as well.
* From GMail you also get the person's signature.

I'm curious, and I might do some digging tomorrow as well, to see if its
possible to strip the last little bit (signature/ads) from email messages.

--00c09fa216eb1bfc0a0479bba823
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

<div class=3D"gmail_quote"><div class=3D"gmail_quote"><div>When sending ema=
il:</div>* From Hotmail you get the ads as well.<div>* Fr=
om GMail you also get the person&#39;s signature.</div><div><br></div><div>=
I'm curious, and I might do some digging tomorrow as well, to see if it=
s possible to strip the last little bit (signature/ads) from email messages=
.<br>

</div></div></div>

--00c09fa216eb1bfc0a0479bba823--
```

So in the text/plain part of the email, there are two bullet points with `*`, which I expected to be converted by MIMEmbellish. 

Through vim, if the message has any accents, then the email is sent, however there is no title nor content.

**Comment by oblitum** [comment]
Are you using utf-8 in Vim?

**Comment by lf-araujo** [comment]
I have that option set as per your previous message.

**Comment by oblitum** [comment]
I see in the email it's stating it's in ISO-8859-1, which is Windows-1252, very common charset for Latin alphabet in Windows land, it's like the plague.

**Comment by oblitum** [comment]
Ah OK, nevermind, it should be just part of the example you're trying.

**Comment by oblitum** [comment]
> I have that option set as per your previous message.

My previous message referred to setting utf-8 on Mutt, but you must also be writing your email file in Vim in utf-8. Check `:set fileencoding`.

**Comment by lf-araujo** [comment]
Will look into it, thanks.

**Comment by lf-araujo** [comment]
Ok, 

I did add the following to my init.vim (for neovim)

```
set fileencoding=us-ascii:utf-8
```

It seems ok, what do you think?

**Comment by lf-araujo** [comment]
Woosh, 

nevermind, the thing started working by itself, your code is a blessing. Thank you!

**Comment by oblitum** [comment]
That's great. You got the basics, don't forget to check the rest in the post, also verify my conf from my dontfiles, not my post, since it may be outdated and I may have fixed stuff in the repo.

**Comment by lf-araujo** [comment]
Unrelated, do you use a script that supports archiving emails in neomutt? I use offlineimap.

**Comment by oblitum** [comment]
Still no, I think it's overkill to me, I don't wish to carry a copy of all my emails. NeoMutt's plain imap support is fine for me, except when connection ins't great, which makes it disconnect from mailbox, doesn't happen a lot but it's a bit annoying. It's on my TODO list to check [aerc](https://github.com/ddevault/aerc) as Mutt replacement. I've also heard of mbsync as offlineimap alternative.
